require: rubocop-minitest

AllCops:
  NewCops: enable
  Exclude:
    - '**/db/schema.rb'
    - '.git/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*_test.rb'

# If you feel annoyed by the current configuration, let's tweak the configuration!
