require: rubocop-minitest

AllCops:
  NewCops: enable
  Exclude:
    - '**/db/schema.rb'
    - '.git/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*_test.rb'

# `assert_equal([], object)` and `assert_equal({}, object)` are completely different,
# so this cop does not make sense to me.
Minitest/AssertEmptyLiteral:
  Enabled: false

# `assert_equal(false, object)` and `assert_equal(nil, object)` are different when it comes to their types,
# so this cop does not make sense to me.
Minitest/RefuteFalse:
  Enabled: false

# If you feel annoyed by the current configuration, let's tweak the configuration!
